name: Workflow CI - Telco Churn Model

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

env:
  CSV_URL: "MLProject/telco_churn_preprocessing"
  DOCKER_IMAGE_NAME: telco-churn-model

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting Workflow CI"

      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 pandas==2.2.3 numpy==2.2.1 scikit-learn==1.6.0

      - name: Run mlflow project
        working-directory: MLProject
        run: |
          mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        working-directory: MLProject
        run: |
          RUN_ID=$(python -c "
          import mlflow
          client = mlflow.tracking.MlflowClient()
          runs = client.search_runs(experiment_ids=['0'], order_by=['start_time DESC'], max_results=1)
          print(runs[0].info.run_id)
          ")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Upload to GitHub (commit mlruns artifact)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f MLProject/mlruns
          git diff --cached --quiet || git commit -m "ci: retrain model, run_id=${{ env.RUN_ID }} [skip ci]"
          git push

      - name: Build Docker Model
        working-directory: MLProject
        run: |
          mlflow models build-docker \
            --model-uri "runs:/${{ env.RUN_ID }}/model" \
            --name "${{ env.DOCKER_IMAGE_NAME }}" \
            --enable-mlserver

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag "${{ env.DOCKER_IMAGE_NAME }}" "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest"

      - name: Push Docker Image
        run: |
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest"

      - name: Complete job
        run: echo "Workflow CI selesai"
